### ISSUE TITLE
Is it legal to host this on Cloud ?

### ISSUE THREAD

**Issue by kdhrubo** [Frooodle/Stirling-PDF#337]
Is there any cloud-hosted version of this product available?
Given that you are using iTEXT - is it even allowed to be hosted on the cloud without a commercial license of iTEXT

**Comment by Frooodle** [comment]
Hmm I was not aware of itext license issues
I will check on this and Remove if required

That's for bringing to attention

**Comment by Frooodle** [comment]
Shouldn't have any issues under there dual license AGPLv3

It is not a commercial product with no software as a service model or purchases from it so I don't see how it would cause issues

**Comment by Frooodle** [comment]
However I will add a note to migrate regardless only 1-3 features use itext

**Comment by Frooodle** [comment]
resolved as part of https://github.com/Frooodle/Stirling-PDF/pull/342/

**Comment by johnricketts** [comment]
Technically there is an issue with using ghostscript as well since it also uses AGPL. However, as far as I am aware you could have kept itext since (I think) GPL3 and AGPL are compatible. OP has misunderstood the requirement, they can host it in cloud as long as they also license their software as AGPL and share the code to all consumers/users.
